name: Add tag

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Hashtag to track"
        required: true

jobs:
  add-tag:
    name: Add tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Add new tag
        run: ./cli.py add-tag $TAG
        env:
          TAG: ${{ github.event.inputs.tagName }}

      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "GitHub Actions"
          message: "Add new tag"
          push: true
